language: node_js
node_js:
  - 'stable'
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build-server
  - cd ./frontEnd
  - npm install
  - npm run test-ci
  - npm run build-client
before_deploy:
  - cd ..
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $heroku_api_key
  app: chris-vita-portfolio
  on:
    all_branches: true
  run:
    - restart